version: '3.8'

services:

  db:
    image: postgres:16.4
    container_name: investor-db
    restart: always
    environment:
      POSTGRES_USER: investor
      POSTGRES_PASSWORD: investor
      POSTGRES_DB: investor
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investor-php
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APP_ENV: dev
    working_dir: /var/www/html

  nginx:
    image: nginx:alpine
    container_name: investor-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

volumes:
  db-data:
