parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            App\Repository\UserRepositoryInterface: '@App\Repository\UserRepository'
            App\Repository\ExchangeRateRepositoryInterface: '@App\Repository\ExchangeRateRepository'
            App\Repository\SymbolRepositoryInterface: '@App\Repository\SymbolRepository'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]
        public: true

    App\State\Processor\ExchangeRate\:
        resource: '../src/State/Processor/ExchangeRate'
        tags: ['app.exchange_rate_processor']
        autowire: true
        autoconfigure: false

    App\State\Processor\:
        resource: '../src/State/Processor'
        exclude: '../src/State/Processor/ExchangeRate'

    App\State\Processor\DataFixture\UserPasswordProcessor:
        tags: [ 'fidry_alice_data_fixtures.processor' ]

    App\State\Processor\SymbolProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
        tags:
            - { name: 'api_platform.state_processor', uriTemplate: '/symbols', priority: 10 }

    App\MessageHandler\UpdateRatesHandler:
        arguments:
            $processors: !tagged_iterator app.exchange_rate_processor

    App\EventSubscriber\:
        resource: '../src/EventSubscriber'
        tags: [ 'doctrine.event_subscriber' ]

    App\Security\ActivationTokenGenerator:
        arguments:
            $appSecret: '%env(APP_SECRET)%'
        public: true

    App\Normalizer\SymbolNormalizer:
        arguments:
            $normalizer: '@serializer.normalizer.object'
        tags: [ 'serializer.normalizer' ]

    Fidry\AliceDataFixtures\LoaderInterface: '@fidry_alice_data_fixtures.doctrine.persister_loader'
